//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelectionInnerContour.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SelectionInnerContour.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Aliasing.
        /// </summary>
        internal static string AntiAliasingString {
            get {
                return ResourceManager.GetString("AntiAliasingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        internal static string BackgroundColorString {
            get {
                return ResourceManager.GetString("BackgroundColorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Opacity.
        /// </summary>
        internal static string BackgroundOpacityString {
            get {
                return ResourceManager.GetString("BackgroundOpacityString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compositing.
        /// </summary>
        internal static string CompositingString {
            get {
                return ResourceManager.GetString("CompositingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Color.
        /// </summary>
        internal static string ForegroundColorString {
            get {
                return ResourceManager.GetString("ForegroundColorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Opacity.
        /// </summary>
        internal static string ForegroundOpacityString {
            get {
                return ResourceManager.GetString("ForegroundOpacityString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient Angle.
        /// </summary>
        internal static string GradientAngleString {
            get {
                return ResourceManager.GetString("GradientAngleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatch Style.
        /// </summary>
        internal static string HatchStyleString {
            get {
                return ResourceManager.GetString("HatchStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Dash Style.
        /// </summary>
        internal static string PenCustomDashStyleString {
            get {
                return ResourceManager.GetString("PenCustomDashStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Cap.
        /// </summary>
        internal static string PenDashCapString {
            get {
                return ResourceManager.GetString("PenDashCapString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dash Style.
        /// </summary>
        internal static string PenDashStyleString {
            get {
                return ResourceManager.GetString("PenDashStyleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Cap.
        /// </summary>
        internal static string PenEndCapString {
            get {
                return ResourceManager.GetString("PenEndCapString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling.
        /// </summary>
        internal static string PenFillingString {
            get {
                return ResourceManager.GetString("PenFillingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Cap.
        /// </summary>
        internal static string PenStartCapString {
            get {
                return ResourceManager.GetString("PenStartCapString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string PenWidthString {
            get {
                return ResourceManager.GetString("PenWidthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Contour.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        internal static string SubmenuName_Selection {
            get {
                return ResourceManager.GetString("SubmenuName_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Image Path.
        /// </summary>
        internal static string TextureImagePathString {
            get {
                return ResourceManager.GetString("TextureImagePathString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Repeat.
        /// </summary>
        internal static string TextureRepeatString {
            get {
                return ResourceManager.GetString("TextureRepeatString", resourceCulture);
            }
        }
    }
}
